### ISSUE TITLE
Add option to add :focus-visible as separate rule for better support.

### ISSUE THREAD

**Issue by andershagbard** [postcss/postcss-focus#24]
`:focus-visible` support is not that great. Currently it is at [91.41% support](https://caniuse.com/css-focus-visible).

In CSS, if one selector is invalid, the entire rule is discarded. This means, for browsers which don't support focus-visible, this entire rule will be discarded, and :hover state will not work.

```css
.myclass:hover,
.myclass:focus-visible {
  background: blue;
}
```

A solution would be to split up the rule. E.g.:
```css
.myclass:hover {
  background: blue;
}

.myclass:focus-visible {
  background:blue;
}

/* or */
.myclass:matches(:focus-visible, :hover) { /* ... */ }
```

Would be nice to at least have this as an option. I am not sure if `:matches` could be a solution.
