### ISSUE TITLE
Add option to specify custom :hover selector?

### ISSUE THREAD

**Issue by FezVrasta** [postcss/postcss-focus#3]
We use [what-input](https://github.com/ten1seven/what-input) to apply the `:focus` effect only when the user is using the keyboard to navigate.

I'd like to use your postcss plugin, but I'd need it to add the proper selector instead of just `:focus`.

Example:

``` css
.my-button:hover {
  background: red;
}

==>

.my-button:hover,
[data-whatinput="keyboard"] .my-button:focus {
  backgroun: red;
}
```

The plugin should then allow us to define a custom pattern, for example:

```
// default pattern
<selector>:focus

// custom pattern
[data-whatinput="keyboard"] <selector>:focus
```

Is it something feasible?
